CCM-1089: PR Bot Fix
NHSDigital/communications-manager pull request #151
Opened 2023-07-26 13:32 UTC by ChewieCB

Updated the bot regex to search for CCM prefixed strings

2023-07-26 13:51 UTC, PhilipSkinner requested changes

2023-07-26 13:51 UTC, PhilipSkinner commented on .github/workflows/pr-lint.yaml
> +        run: echo ${{ github.event.pull_request.head.ref }} | grep -i -E -q "(ccm-[0-9]+)|(apmspii-[0-9]+)|(adz-[0-9]+)|(ccm-[0-9]+)|(dependabot\/)"
can simplify this to remove the apmspii, adz and duplicated ccm regexes

2023-07-26 13:51 UTC, PhilipSkinner commented on .github/workflows/pr-lint.yaml
> +        if: contains(github.event.pull_request.head.ref, 'ccm-') || contains(github.event.pull_request.head.ref, 'CCM-') || contains(github.event.pull_request.head.ref, 'apmspii-') || contains(github
same here, remove the irrelevant checks for apmspii, adz and the duplicate CCM checks

2023-07-26 13:51 UTC, PhilipSkinner commented on .github/workflows/pr-lint.yaml
> +        if: contains(github.event.pull_request.head.ref, 'ccm-') || contains(github.event.pull_request.head.ref, 'CCM-') || contains(github.event.pull_request.head.ref, 'apmspii-') || contains(github
same here, remove the irrelevant checks for apmspii, adz and the duplicate ccm checks

2023-07-27 14:17 UTC, Kennedy1265 approved these changes

2023-08-01 08:29 UTC, ChewieCB commented
/azp run

2023-08-01 09:18 UTC, merged